<?php
/**
 * BoulangeriesApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use Swagger\Server\Configuration;
use Swagger\Server\ApiClient;
use Swagger\Server\ApiException;
use Swagger\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * BoulangeriesApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BoulangeriesApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addBoulangerie
     *
     * Add a new boulangerie.
     *
     */
    public function testAddBoulangerie()
    {
        $client = static::createClient();

        $path = '/boulangeries';

        $crawler = $client->request('POST', $path);
    }

    /**
     * Test case for deleteBoulangerie
     *
     * deletes Boulangerie by id.
     *
     */
    public function testDeleteBoulangerie()
    {
        $client = static::createClient();

        $path = '/boulangeries/ById/{idBoulangerie}';
        $pattern = '{idBoulangerie}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
    }

    /**
     * Test case for getBoulangerieById
     *
     * returns one Boulangerie by ID.
     *
     */
    public function testGetBoulangerieById()
    {
        $client = static::createClient();

        $path = '/boulangeries/ById/{idBoulangerie}';
        $pattern = '{idBoulangerie}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getBoulangerieByMatricule
     *
     * returns one Boulangerie by Matricule of Responsable.
     *
     */
    public function testGetBoulangerieByMatricule()
    {
        $client = static::createClient();

        $path = '/boulangeries/{matricule}';
        $pattern = '{matricule}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getBoulangeries
     *
     * get all boulangeries.
     *
     */
    public function testGetBoulangeries()
    {
        $client = static::createClient();

        $path = '/boulangeries';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for updateAndReplaceBoulangerie
     *
     * replaces Boulangerie by Updated version.
     *
     */
    public function testUpdateAndReplaceBoulangerie()
    {
        $client = static::createClient();

        $path = '/boulangeries/ById/{idBoulangerie}';
        $pattern = '{idBoulangerie}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('PUT', $path);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast); 
    }
}
