<?php
/**
 * LivreursApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use Swagger\Server\Configuration;
use Swagger\Server\ApiClient;
use Swagger\Server\ApiException;
use Swagger\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * LivreursApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LivreursApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLivreur
     *
     * Add a new livreur.
     *
     */
    public function testAddLivreur()
    {
        $client = static::createClient();

        $path = '/livreurs';

        $crawler = $client->request('POST', $path);
    }

    /**
     * Test case for deleteLivreurbyMatricule
     *
     * Deletes a livreur by matricule.
     *
     */
    public function testDeleteLivreurbyMatricule()
    {
        $client = static::createClient();

        $path = '/livreurs/{matricule}';
        $pattern = '{matricule}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
    }

    /**
     * Test case for getLivreurs
     *
     * get all livreurs.
     *
     */
    public function testGetLivreurs()
    {
        $client = static::createClient();

        $path = '/livreurs';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getLivreursByMatricule
     *
     * .
     *
     */
    public function testGetLivreursByMatricule()
    {
        $client = static::createClient();

        $path = '/livreurs/{matricule}';
        $pattern = '{matricule}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for updateLivreur
     *
     * .
     *
     */
    public function testUpdateLivreur()
    {
        $client = static::createClient();

        $path = '/livreurs/{matricule}';
        $pattern = '{matricule}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('PUT', $path);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast); 
    }
}
