<?php
/**
 * ProduitsApiInterfaceTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Server\Tests\Api;

use Swagger\Server\Configuration;
use Swagger\Server\ApiClient;
use Swagger\Server\ApiException;
use Swagger\Server\ObjectSerializer;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * ProduitsApiInterfaceTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Server\Tests\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProduitsApiInterfaceTest extends WebTestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addProduit
     *
     * Add a new produit.
     *
     */
    public function testAddProduit()
    {
        $client = static::createClient();

        $path = '/produits';

        $crawler = $client->request('POST', $path);
    }

    /**
     * Test case for deleteProduitByCodeProduit
     *
     * Deletes a produit by its code.
     *
     */
    public function testDeleteProduitByCodeProduit()
    {
        $client = static::createClient();

        $path = '/produits/{codeProduit}';
        $pattern = '{codeProduit}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('DELETE', $path);
    }

    /**
     * Test case for getCompositionsOfProduit
     *
     * get compositons filtered collection with quantity for a certain produit.
     *
     */
    public function testGetCompositionsOfProduit()
    {
        $client = static::createClient();

        $path = '/produits/{codeProduit}/compositionsProduit';
        $pattern = '{codeProduit}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getProduitByCodeProduit
     *
     * get one produit.
     *
     */
    public function testGetProduitByCodeProduit()
    {
        $client = static::createClient();

        $path = '/produits/{codeProduit}';
        $pattern = '{codeProduit}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for getProduits
     *
     * get all produits.
     *
     */
    public function testGetProduits()
    {
        $client = static::createClient();

        $path = '/produits';

        $crawler = $client->request('GET', $path);
    }

    /**
     * Test case for updateAndReplaceProduit
     *
     * replaces Produit by Updated version.
     *
     */
    public function testUpdateAndReplaceProduit()
    {
        $client = static::createClient();

        $path = '/produits/{codeProduit}';
        $pattern = '{codeProduit}';
        $data = $this->genTestData('\d+');
        $path = str_replace($pattern, $data, $path);

        $crawler = $client->request('PUT', $path);
    }

    protected function genTestData($regexp)
    {
        $grammar  = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
        $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
        $ast      = $compiler->parse($regexp);
        $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

        return $generator->visit($ast); 
    }
}
