<?php
/**
 * BoulangeriesApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\Boulangeries;
use Swagger\Server\Model\InlineResponse2001;

/**
 * BoulangeriesApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface BoulangeriesApiInterface
{

    /**
     * Operation addBoulangerie
     *
     * Add a new boulangerie
     *
     * @param  Swagger\Server\Model\Boulangeries $body  boulangerie object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addBoulangerie(Boulangeries $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteBoulangerie
     *
     * deletes Boulangerie by id
     *
     * @param  int $idBoulangerie   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteBoulangerie($idBoulangerie, &$responseCode, array &$responseHeaders);

    /**
     * Operation getBoulangerieById
     *
     * returns one Boulangerie by ID
     *
     * @param  int $idBoulangerie   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Boulangeries[]
     *
     */
    public function getBoulangerieById($idBoulangerie, &$responseCode, array &$responseHeaders);

    /**
     * Operation getBoulangerieByMatricule
     *
     * returns one Boulangerie by Matricule of Responsable
     *
     * @param  int $matricule   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Boulangeries[]
     *
     */
    public function getBoulangerieByMatricule($matricule, &$responseCode, array &$responseHeaders);

    /**
     * Operation getBoulangeries
     *
     * get all boulangeries
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\InlineResponse2001[]
     *
     */
    public function getBoulangeries(&$responseCode, array &$responseHeaders);

    /**
     * Operation updateAndReplaceBoulangerie
     *
     * replaces Boulangerie by Updated version
     *
     * @param  int $idBoulangerie   (required)
     * @param  Swagger\Server\Model\Boulangeries $body  updated boulangerie object (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function updateAndReplaceBoulangerie($idBoulangerie, Boulangeries $body, &$responseCode, array &$responseHeaders);
}
