<?php
/**
 * ComposantsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\Composants;

/**
 * ComposantsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface ComposantsApiInterface
{

    /**
     * Operation addComposant
     *
     * add Composant Object
     *
     * @param  Swagger\Server\Model\Composants $body  Composant object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addComposant(Composants $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation composantsIdComposantGet
     *
     * get composant by id
     *
     * @param  string $idComposant   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Composants[]
     *
     */
    public function composantsIdComposantGet($idComposant, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteComposantById
     *
     * Deletes a composant by id
     *
     * @param  string $idComposant  composant id to delete (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteComposantById($idComposant, &$responseCode, array &$responseHeaders);

    /**
     * Operation getComposants
     *
     * get all composants
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Composants[]
     *
     */
    public function getComposants(&$responseCode, array &$responseHeaders);
}
