<?php
/**
 * CompositionsProduitApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\CompositionsProduit;

/**
 * CompositionsProduitApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface CompositionsProduitApiInterface
{

    /**
     * Operation addCompositionProduit
     *
     * create new CompositionProduit
     *
     * @param  Swagger\Server\Model\CompositionsProduit $body  CompositionsProduit object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addCompositionProduit(CompositionsProduit $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteCompositionByProduitAndComposant
     *
     * Deletes a compositionProduit by codeProduit and idComposant
     *
     * @param  int $codeProduit   (required)
     * @param  string $idComposant   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteCompositionByProduitAndComposant($codeProduit, $idComposant, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteCompositionsProduitById
     *
     * Deletes a compositionProduit by its ID
     *
     * @param  int $idComposition  CompositionProduit Id to delete (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteCompositionsProduitById($idComposition, &$responseCode, array &$responseHeaders);

    /**
     * Operation getCompositionsProduit
     *
     * get compositionsProduit
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\CompositionsProduit[]
     *
     */
    public function getCompositionsProduit(&$responseCode, array &$responseHeaders);
}
