<?php
/**
 * LivreursApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\InlineResponse200;
use Swagger\Server\Model\Livreurs;

/**
 * LivreursApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface LivreursApiInterface
{

    /**
     * Operation addLivreur
     *
     * Add a new livreur
     *
     * @param  Swagger\Server\Model\Livreurs $body  Livreur object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addLivreur(Livreurs $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteLivreurbyMatricule
     *
     * Deletes a livreur by matricule
     *
     * @param  int $matricule  livreur matricule to delete (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteLivreurbyMatricule($matricule, &$responseCode, array &$responseHeaders);

    /**
     * Operation getLivreurs
     *
     * get all livreurs
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\InlineResponse200[]
     *
     */
    public function getLivreurs(&$responseCode, array &$responseHeaders);

    /**
     * Operation getLivreursByMatricule
     *
     * @param  int $matricule   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Livreurs[]
     *
     */
    public function getLivreursByMatricule($matricule, &$responseCode, array &$responseHeaders);

    /**
     * Operation updateLivreur
     *
     * @param  int $matricule   (required)
     * @param  Swagger\Server\Model\Livreurs $body  The updated livreur version (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function updateLivreur($matricule, Livreurs $body, &$responseCode, array &$responseHeaders);
}
