<?php
/**
 * ProfilsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Swagger\Server\Model\Produits;
use Swagger\Server\Model\Profils;

/**
 * ProfilsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  Swagger\Server\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
interface ProfilsApiInterface
{

    /**
     * Operation addProfil
     *
     * Add a new profil to the system
     *
     * @param  Swagger\Server\Model\Profils $body  profil object that needs to be added (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function addProfil(Profils $body, &$responseCode, array &$responseHeaders);

    /**
     * Operation deleteProfilByMatricule
     *
     * Deletes a profil
     *
     * @param  int $matricule  Profil matricule to delete (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function deleteProfilByMatricule($matricule, &$responseCode, array &$responseHeaders);

    /**
     * Operation getProfilByLogin
     *
     * Find profil by Login
     *
     * @param  string $login  login of profil to return (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Produits[]
     *
     */
    public function getProfilByLogin($login, &$responseCode, array &$responseHeaders);

    /**
     * Operation getProfilByMatricule
     *
     * gets a profil by matricule
     *
     * @param  int $matricule   (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Profils[]
     *
     */
    public function getProfilByMatricule($matricule, &$responseCode, array &$responseHeaders);

    /**
     * Operation getProfils
     *
     * get all profils
     *
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return Swagger\Server\Model\Profils[]
     *
     */
    public function getProfils(&$responseCode, array &$responseHeaders);
}
