<?php
/**
 * Administrateurs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Administrateurs model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Administrateurs 
{
        /**
     * @var string
     * @SerializedName("loginAdmin")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $loginAdmin;

    /**
     * @var string
     * @SerializedName("passwordAdmin")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $passwordAdmin;

    /**
     * @var string|null
     * @SerializedName("nomAdmin")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nomAdmin;

    /**
     * @var int|null
     * @SerializedName("teleAdmin")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $teleAdmin;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->loginAdmin = isset($data['loginAdmin']) ? $data['loginAdmin'] : null;
        $this->passwordAdmin = isset($data['passwordAdmin']) ? $data['passwordAdmin'] : null;
        $this->nomAdmin = isset($data['nomAdmin']) ? $data['nomAdmin'] : null;
        $this->teleAdmin = isset($data['teleAdmin']) ? $data['teleAdmin'] : null;
    }

    /**
     * Gets loginAdmin.
     *
     * @return string
     */
    public function getLoginAdmin()
    {
        return $this->loginAdmin;
    }

    /**
     * Sets loginAdmin.
     *
     * @param string $loginAdmin
     *
     * @return $this
     */
    public function setLoginAdmin($loginAdmin)
    {
        $this->loginAdmin = $loginAdmin;

        return $this;
    }

    /**
     * Gets passwordAdmin.
     *
     * @return string
     */
    public function getPasswordAdmin()
    {
        return $this->passwordAdmin;
    }

    /**
     * Sets passwordAdmin.
     *
     * @param string $passwordAdmin
     *
     * @return $this
     */
    public function setPasswordAdmin($passwordAdmin)
    {
        $this->passwordAdmin = $passwordAdmin;

        return $this;
    }

    /**
     * Gets nomAdmin.
     *
     * @return string|null
     */
    public function getNomAdmin()
    {
        return $this->nomAdmin;
    }

    /**
     * Sets nomAdmin.
     *
     * @param string|null $nomAdmin
     *
     * @return $this
     */
    public function setNomAdmin($nomAdmin = null)
    {
        $this->nomAdmin = $nomAdmin;

        return $this;
    }

    /**
     * Gets teleAdmin.
     *
     * @return int|null
     */
    public function getTeleAdmin()
    {
        return $this->teleAdmin;
    }

    /**
     * Sets teleAdmin.
     *
     * @param int|null $teleAdmin
     *
     * @return $this
     */
    public function setTeleAdmin($teleAdmin = null)
    {
        $this->teleAdmin = $teleAdmin;

        return $this;
    }
}


