<?php
/**
 * Boulangeries
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Boulangeries model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Boulangeries 
{
        /**
     * @var int
     * @SerializedName("idBoulangerie")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idBoulangerie;

    /**
     * @var string
     * @SerializedName("nomBL")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 50
     * )
     */
    protected $nomBL;

    /**
     * @var string|null
     * @SerializedName("adresse")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 50
     * )
     */
    protected $adresse;

    /**
     * @var int|null
     * @SerializedName("telephone")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $telephone;

    /**
     * @var int|null
     * @SerializedName("matricule")
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\LessThanOrEqual(9999)
     */
    protected $matricule;

    /**
     * @var int|null
     * @SerializedName("nbOperateurs")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $nbOperateurs;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idBoulangerie = isset($data['idBoulangerie']) ? $data['idBoulangerie'] : null;
        $this->nomBL = isset($data['nomBL']) ? $data['nomBL'] : null;
        $this->adresse = isset($data['adresse']) ? $data['adresse'] : null;
        $this->telephone = isset($data['telephone']) ? $data['telephone'] : null;
        $this->matricule = isset($data['matricule']) ? $data['matricule'] : null;
        $this->nbOperateurs = isset($data['nbOperateurs']) ? $data['nbOperateurs'] : null;
    }

    /**
     * Gets idBoulangerie.
     *
     * @return int
     */
    public function getIdBoulangerie()
    {
        return $this->idBoulangerie;
    }

    /**
     * Sets idBoulangerie.
     *
     * @param int $idBoulangerie
     *
     * @return $this
     */
    public function setIdBoulangerie($idBoulangerie)
    {
        $this->idBoulangerie = $idBoulangerie;

        return $this;
    }

    /**
     * Gets nomBL.
     *
     * @return string
     */
    public function getNomBL()
    {
        return $this->nomBL;
    }

    /**
     * Sets nomBL.
     *
     * @param string $nomBL
     *
     * @return $this
     */
    public function setNomBL($nomBL)
    {
        $this->nomBL = $nomBL;

        return $this;
    }

    /**
     * Gets adresse.
     *
     * @return string|null
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Sets adresse.
     *
     * @param string|null $adresse
     *
     * @return $this
     */
    public function setAdresse($adresse = null)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Gets telephone.
     *
     * @return int|null
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * Sets telephone.
     *
     * @param int|null $telephone
     *
     * @return $this
     */
    public function setTelephone($telephone = null)
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * Gets matricule.
     *
     * @return int|null
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * Sets matricule.
     *
     * @param int|null $matricule
     *
     * @return $this
     */
    public function setMatricule($matricule = null)
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * Gets nbOperateurs.
     *
     * @return int|null
     */
    public function getNbOperateurs()
    {
        return $this->nbOperateurs;
    }

    /**
     * Sets nbOperateurs.
     *
     * @param int|null $nbOperateurs
     *
     * @return $this
     */
    public function setNbOperateurs($nbOperateurs = null)
    {
        $this->nbOperateurs = $nbOperateurs;

        return $this;
    }
}


