<?php
/**
 * CommandesLabo
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CommandesLabo model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CommandesLabo 
{
        /**
     * @var int|null
     * @SerializedName("idCommandesLabo")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idCommandesLabo;

    /**
     * @var int
     * @SerializedName("codeProduit")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string|null
     * @SerializedName("libelle")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 10
     * )
     */
    protected $libelle;

    /**
     * @var \DateTime
     * @SerializedName("dueDate")
     * @Assert\NotNull()
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $dueDate;

    /**
     * @var string|null
     * @SerializedName("quantiteTotal")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $quantiteTotal;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idCommandesLabo = isset($data['idCommandesLabo']) ? $data['idCommandesLabo'] : null;
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->libelle = isset($data['libelle']) ? $data['libelle'] : null;
        $this->dueDate = isset($data['dueDate']) ? $data['dueDate'] : null;
        $this->quantiteTotal = isset($data['quantiteTotal']) ? $data['quantiteTotal'] : null;
    }

    /**
     * Gets idCommandesLabo.
     *
     * @return int|null
     */
    public function getIdCommandesLabo()
    {
        return $this->idCommandesLabo;
    }

    /**
     * Sets idCommandesLabo.
     *
     * @param int|null $idCommandesLabo
     *
     * @return $this
     */
    public function setIdCommandesLabo($idCommandesLabo = null)
    {
        $this->idCommandesLabo = $idCommandesLabo;

        return $this;
    }

    /**
     * Gets codeProduit.
     *
     * @return int
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets libelle.
     *
     * @return string|null
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Sets libelle.
     *
     * @param string|null $libelle
     *
     * @return $this
     */
    public function setLibelle($libelle = null)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Gets dueDate.
     *
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * Sets dueDate.
     *
     * @param \DateTime $dueDate
     *
     * @return $this
     */
    public function setDueDate(\DateTime $dueDate)
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    /**
     * Gets quantiteTotal.
     *
     * @return string|null
     */
    public function getQuantiteTotal()
    {
        return $this->quantiteTotal;
    }

    /**
     * Sets quantiteTotal.
     *
     * @param string|null $quantiteTotal
     *
     * @return $this
     */
    public function setQuantiteTotal($quantiteTotal = null)
    {
        $this->quantiteTotal = $quantiteTotal;

        return $this;
    }
}


