<?php
/**
 * CommandesBL
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CommandesBL model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CommandesBL 
{
        /**
     * @var string
     * @SerializedName("idCommandeBL")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 20
     * )
     */
    protected $idCommandeBL;

    /**
     * @var \DateTime
     * @SerializedName("dueDate")
     * @Assert\NotNull()
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $dueDate;

    /**
     * @var \DateTime|null
     * @SerializedName("creationDate")
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $creationDate;

    /**
     * etat Commande
     *
     * @var string|null
     * @SerializedName("etat")
     * @Assert\Choice({ "nouvelle", "enCours", "honoree" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $etat;

    /**
     * @var int
     * @SerializedName("idBoulangerie")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idBoulangerie;

    /**
     * @var int|null
     * @SerializedName("matricule")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $matricule;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idCommandeBL = isset($data['idCommandeBL']) ? $data['idCommandeBL'] : null;
        $this->dueDate = isset($data['dueDate']) ? $data['dueDate'] : null;
        $this->creationDate = isset($data['creationDate']) ? $data['creationDate'] : null;
        $this->etat = isset($data['etat']) ? $data['etat'] : null;
        $this->idBoulangerie = isset($data['idBoulangerie']) ? $data['idBoulangerie'] : null;
        $this->matricule = isset($data['matricule']) ? $data['matricule'] : null;
    }

    /**
     * Gets idCommandeBL.
     *
     * @return string
     */
    public function getIdCommandeBL()
    {
        return $this->idCommandeBL;
    }

    /**
     * Sets idCommandeBL.
     *
     * @param string $idCommandeBL
     *
     * @return $this
     */
    public function setIdCommandeBL($idCommandeBL)
    {
        $this->idCommandeBL = $idCommandeBL;

        return $this;
    }

    /**
     * Gets dueDate.
     *
     * @return \DateTime
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * Sets dueDate.
     *
     * @param \DateTime $dueDate
     *
     * @return $this
     */
    public function setDueDate(\DateTime $dueDate)
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    /**
     * Gets creationDate.
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Sets creationDate.
     *
     * @param \DateTime|null $creationDate
     *
     * @return $this
     */
    public function setCreationDate(\DateTime $creationDate = null)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Gets etat.
     *
     * @return string|null
     */
    public function getEtat()
    {
        return $this->etat;
    }

    /**
     * Sets etat.
     *
     * @param string|null $etat  etat Commande
     *
     * @return $this
     */
    public function setEtat($etat = null)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Gets idBoulangerie.
     *
     * @return int
     */
    public function getIdBoulangerie()
    {
        return $this->idBoulangerie;
    }

    /**
     * Sets idBoulangerie.
     *
     * @param int $idBoulangerie
     *
     * @return $this
     */
    public function setIdBoulangerie($idBoulangerie)
    {
        $this->idBoulangerie = $idBoulangerie;

        return $this;
    }

    /**
     * Gets matricule.
     *
     * @return int|null
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * Sets matricule.
     *
     * @param int|null $matricule
     *
     * @return $this
     */
    public function setMatricule($matricule = null)
    {
        $this->matricule = $matricule;

        return $this;
    }
}


