<?php
/**
 * CompositionsProduit
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the CompositionsProduit model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class CompositionsProduit 
{
        /**
     * @var int
     * @SerializedName("idComposition")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idComposition;

    /**
     * @var int
     * @SerializedName("codeProduit")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string
     * @SerializedName("idComposant")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $idComposant;

    /**
     * @var int
     * @SerializedName("quantiteComp")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $quantiteComp;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idComposition = isset($data['idComposition']) ? $data['idComposition'] : null;
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->idComposant = isset($data['idComposant']) ? $data['idComposant'] : null;
        $this->quantiteComp = isset($data['quantiteComp']) ? $data['quantiteComp'] : null;
    }

    /**
     * Gets idComposition.
     *
     * @return int
     */
    public function getIdComposition()
    {
        return $this->idComposition;
    }

    /**
     * Sets idComposition.
     *
     * @param int $idComposition
     *
     * @return $this
     */
    public function setIdComposition($idComposition)
    {
        $this->idComposition = $idComposition;

        return $this;
    }

    /**
     * Gets codeProduit.
     *
     * @return int
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets idComposant.
     *
     * @return string
     */
    public function getIdComposant()
    {
        return $this->idComposant;
    }

    /**
     * Sets idComposant.
     *
     * @param string $idComposant
     *
     * @return $this
     */
    public function setIdComposant($idComposant)
    {
        $this->idComposant = $idComposant;

        return $this;
    }

    /**
     * Gets quantiteComp.
     *
     * @return int
     */
    public function getQuantiteComp()
    {
        return $this->quantiteComp;
    }

    /**
     * Sets quantiteComp.
     *
     * @param int $quantiteComp
     *
     * @return $this
     */
    public function setQuantiteComp($quantiteComp)
    {
        $this->quantiteComp = $quantiteComp;

        return $this;
    }
}


