<?php
/**
 * Composants
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Composants model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Composants 
{
        /**
     * @var string
     * @SerializedName("idComposant")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 6
     * )
     */
    protected $idComposant;

    /**
     * @var string
     * @SerializedName("nomComp")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 20
     * )
     */
    protected $nomComp;

    /**
     * @var string|null
     * @SerializedName("unite")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 20
     * )
     */
    protected $unite;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idComposant = isset($data['idComposant']) ? $data['idComposant'] : null;
        $this->nomComp = isset($data['nomComp']) ? $data['nomComp'] : null;
        $this->unite = isset($data['unite']) ? $data['unite'] : null;
    }

    /**
     * Gets idComposant.
     *
     * @return string
     */
    public function getIdComposant()
    {
        return $this->idComposant;
    }

    /**
     * Sets idComposant.
     *
     * @param string $idComposant
     *
     * @return $this
     */
    public function setIdComposant($idComposant)
    {
        $this->idComposant = $idComposant;

        return $this;
    }

    /**
     * Gets nomComp.
     *
     * @return string
     */
    public function getNomComp()
    {
        return $this->nomComp;
    }

    /**
     * Sets nomComp.
     *
     * @param string $nomComp
     *
     * @return $this
     */
    public function setNomComp($nomComp)
    {
        $this->nomComp = $nomComp;

        return $this;
    }

    /**
     * Gets unite.
     *
     * @return string|null
     */
    public function getUnite()
    {
        return $this->unite;
    }

    /**
     * Sets unite.
     *
     * @param string|null $unite
     *
     * @return $this
     */
    public function setUnite($unite = null)
    {
        $this->unite = $unite;

        return $this;
    }
}


