<?php
/**
 * DetailsCommandesBL
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the DetailsCommandesBL model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class DetailsCommandesBL 
{
        /**
     * @var int
     * @SerializedName("idDetail")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idDetail;

    /**
     * @var int
     * @SerializedName("codeProduit")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string
     * @SerializedName("idCommandeBL")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $idCommandeBL;

    /**
     * @var int
     * @SerializedName("quantiteProd")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $quantiteProd;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idDetail = isset($data['idDetail']) ? $data['idDetail'] : null;
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->idCommandeBL = isset($data['idCommandeBL']) ? $data['idCommandeBL'] : null;
        $this->quantiteProd = isset($data['quantiteProd']) ? $data['quantiteProd'] : null;
    }

    /**
     * Gets idDetail.
     *
     * @return int
     */
    public function getIdDetail()
    {
        return $this->idDetail;
    }

    /**
     * Sets idDetail.
     *
     * @param int $idDetail
     *
     * @return $this
     */
    public function setIdDetail($idDetail)
    {
        $this->idDetail = $idDetail;

        return $this;
    }

    /**
     * Gets codeProduit.
     *
     * @return int
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets idCommandeBL.
     *
     * @return string
     */
    public function getIdCommandeBL()
    {
        return $this->idCommandeBL;
    }

    /**
     * Sets idCommandeBL.
     *
     * @param string $idCommandeBL
     *
     * @return $this
     */
    public function setIdCommandeBL($idCommandeBL)
    {
        $this->idCommandeBL = $idCommandeBL;

        return $this;
    }

    /**
     * Gets quantiteProd.
     *
     * @return int
     */
    public function getQuantiteProd()
    {
        return $this->quantiteProd;
    }

    /**
     * Sets quantiteProd.
     *
     * @param int $quantiteProd
     *
     * @return $this
     */
    public function setQuantiteProd($quantiteProd)
    {
        $this->quantiteProd = $quantiteProd;

        return $this;
    }
}


