<?php
/**
 * InlineResponse2003
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse2003 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse2003 
{
        /**
     * @var int|null
     * @SerializedName("codeProduit")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string|null
     * @SerializedName("libelle")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $libelle;

    /**
     * @var \DateTime|null
     * @SerializedName("dueDate")
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $dueDate;

    /**
     * @var int|null
     * @SerializedName("sumQuantite")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $sumQuantite;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->libelle = isset($data['libelle']) ? $data['libelle'] : null;
        $this->dueDate = isset($data['dueDate']) ? $data['dueDate'] : null;
        $this->sumQuantite = isset($data['sumQuantite']) ? $data['sumQuantite'] : null;
    }

    /**
     * Gets codeProduit.
     *
     * @return int|null
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int|null $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit = null)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets libelle.
     *
     * @return string|null
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Sets libelle.
     *
     * @param string|null $libelle
     *
     * @return $this
     */
    public function setLibelle($libelle = null)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Gets dueDate.
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * Sets dueDate.
     *
     * @param \DateTime|null $dueDate
     *
     * @return $this
     */
    public function setDueDate(\DateTime $dueDate = null)
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    /**
     * Gets sumQuantite.
     *
     * @return int|null
     */
    public function getSumQuantite()
    {
        return $this->sumQuantite;
    }

    /**
     * Sets sumQuantite.
     *
     * @param int|null $sumQuantite
     *
     * @return $this
     */
    public function setSumQuantite($sumQuantite = null)
    {
        $this->sumQuantite = $sumQuantite;

        return $this;
    }
}


