<?php
/**
 * InlineResponse2004
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse2004 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse2004 
{
        /**
     * @var int|null
     * @SerializedName("codeProduit")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string|null
     * @SerializedName("libelle")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $libelle;

    /**
     * @var int|null
     * @SerializedName("quantiteProd")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $quantiteProd;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->libelle = isset($data['libelle']) ? $data['libelle'] : null;
        $this->quantiteProd = isset($data['quantiteProd']) ? $data['quantiteProd'] : null;
    }

    /**
     * Gets codeProduit.
     *
     * @return int|null
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int|null $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit = null)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets libelle.
     *
     * @return string|null
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Sets libelle.
     *
     * @param string|null $libelle
     *
     * @return $this
     */
    public function setLibelle($libelle = null)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Gets quantiteProd.
     *
     * @return int|null
     */
    public function getQuantiteProd()
    {
        return $this->quantiteProd;
    }

    /**
     * Sets quantiteProd.
     *
     * @param int|null $quantiteProd
     *
     * @return $this
     */
    public function setQuantiteProd($quantiteProd = null)
    {
        $this->quantiteProd = $quantiteProd;

        return $this;
    }
}


