<?php
/**
 * InlineResponse2005
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse2005 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse2005 
{
        /**
     * @var Swagger\Server\Model\Composants|null
     * @SerializedName("Composant")
     * @Assert\Type("Swagger\Server\Model\Composants")
     * @Type("Swagger\Server\Model\Composants")
     */
    protected $composant;

    /**
     * @var int|null
     * @SerializedName("quantiteComp")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $quantiteComp;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->composant = isset($data['composant']) ? $data['composant'] : null;
        $this->quantiteComp = isset($data['quantiteComp']) ? $data['quantiteComp'] : null;
    }

    /**
     * Gets composant.
     *
     * @return Swagger\Server\Model\Composants|null
     */
    public function getComposant()
    {
        return $this->composant;
    }

    /**
     * Sets composant.
     *
     * @param Swagger\Server\Model\Composants|null $composant
     *
     * @return $this
     */
    public function setComposant(Composants $composant = null)
    {
        $this->composant = $composant;

        return $this;
    }

    /**
     * Gets quantiteComp.
     *
     * @return int|null
     */
    public function getQuantiteComp()
    {
        return $this->quantiteComp;
    }

    /**
     * Sets quantiteComp.
     *
     * @param int|null $quantiteComp
     *
     * @return $this
     */
    public function setQuantiteComp($quantiteComp = null)
    {
        $this->quantiteComp = $quantiteComp;

        return $this;
    }
}


