<?php
/**
 * InlineResponse200
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse200 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse200 
{
        /**
     * @var string|null
     * @SerializedName("nom")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nom;

    /**
     * @var Swagger\Server\Model\Livreurs|null
     * @SerializedName("livreur")
     * @Assert\Type("Swagger\Server\Model\Livreurs")
     * @Type("Swagger\Server\Model\Livreurs")
     */
    protected $livreur;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->nom = isset($data['nom']) ? $data['nom'] : null;
        $this->livreur = isset($data['livreur']) ? $data['livreur'] : null;
    }

    /**
     * Gets nom.
     *
     * @return string|null
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Sets nom.
     *
     * @param string|null $nom
     *
     * @return $this
     */
    public function setNom($nom = null)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Gets livreur.
     *
     * @return Swagger\Server\Model\Livreurs|null
     */
    public function getLivreur()
    {
        return $this->livreur;
    }

    /**
     * Sets livreur.
     *
     * @param Swagger\Server\Model\Livreurs|null $livreur
     *
     * @return $this
     */
    public function setLivreur(Livreurs $livreur = null)
    {
        $this->livreur = $livreur;

        return $this;
    }
}


