<?php
/**
 * InlineResponse2002
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse2002 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse2002 
{
        /**
     * @var string|null
     * @SerializedName("idCommandeBL")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $idCommandeBL;

    /**
     * @var \DateTime|null
     * @SerializedName("creationDate")
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $creationDate;

    /**
     * @var \DateTime|null
     * @SerializedName("dueDate")
     * @Assert\Date()
     * @Type("DateTime")
     */
    protected $dueDate;

    /**
     * @var int|null
     * @SerializedName("idBoulangerie")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $idBoulangerie;

    /**
     * @var string|null
     * @SerializedName("nomBL")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nomBL;

    /**
     * matricule livreur from cmd
     *
     * @var int|null
     * @SerializedName("matricule")
     * @Assert\Type("int")
     * @Type("int")
     * @Assert\GreaterThanOrEqual(0)
     * @Assert\LessThanOrEqual(9999)
     */
    protected $matricule;

    /**
     * nom correspondant a la matricule (from profil)
     *
     * @var string|null
     * @SerializedName("nom")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nom;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->idCommandeBL = isset($data['idCommandeBL']) ? $data['idCommandeBL'] : null;
        $this->creationDate = isset($data['creationDate']) ? $data['creationDate'] : null;
        $this->dueDate = isset($data['dueDate']) ? $data['dueDate'] : null;
        $this->idBoulangerie = isset($data['idBoulangerie']) ? $data['idBoulangerie'] : null;
        $this->nomBL = isset($data['nomBL']) ? $data['nomBL'] : null;
        $this->matricule = isset($data['matricule']) ? $data['matricule'] : null;
        $this->nom = isset($data['nom']) ? $data['nom'] : null;
    }

    /**
     * Gets idCommandeBL.
     *
     * @return string|null
     */
    public function getIdCommandeBL()
    {
        return $this->idCommandeBL;
    }

    /**
     * Sets idCommandeBL.
     *
     * @param string|null $idCommandeBL
     *
     * @return $this
     */
    public function setIdCommandeBL($idCommandeBL = null)
    {
        $this->idCommandeBL = $idCommandeBL;

        return $this;
    }

    /**
     * Gets creationDate.
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Sets creationDate.
     *
     * @param \DateTime|null $creationDate
     *
     * @return $this
     */
    public function setCreationDate(\DateTime $creationDate = null)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Gets dueDate.
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->dueDate;
    }

    /**
     * Sets dueDate.
     *
     * @param \DateTime|null $dueDate
     *
     * @return $this
     */
    public function setDueDate(\DateTime $dueDate = null)
    {
        $this->dueDate = $dueDate;

        return $this;
    }

    /**
     * Gets idBoulangerie.
     *
     * @return int|null
     */
    public function getIdBoulangerie()
    {
        return $this->idBoulangerie;
    }

    /**
     * Sets idBoulangerie.
     *
     * @param int|null $idBoulangerie
     *
     * @return $this
     */
    public function setIdBoulangerie($idBoulangerie = null)
    {
        $this->idBoulangerie = $idBoulangerie;

        return $this;
    }

    /**
     * Gets nomBL.
     *
     * @return string|null
     */
    public function getNomBL()
    {
        return $this->nomBL;
    }

    /**
     * Sets nomBL.
     *
     * @param string|null $nomBL
     *
     * @return $this
     */
    public function setNomBL($nomBL = null)
    {
        $this->nomBL = $nomBL;

        return $this;
    }

    /**
     * Gets matricule.
     *
     * @return int|null
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * Sets matricule.
     *
     * @param int|null $matricule  matricule livreur from cmd
     *
     * @return $this
     */
    public function setMatricule($matricule = null)
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * Gets nom.
     *
     * @return string|null
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Sets nom.
     *
     * @param string|null $nom  nom correspondant a la matricule (from profil)
     *
     * @return $this
     */
    public function setNom($nom = null)
    {
        $this->nom = $nom;

        return $this;
    }
}


