<?php
/**
 * InlineResponse2001
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the InlineResponse2001 model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class InlineResponse2001 
{
        /**
     * @var Swagger\Server\Model\Boulangeries|null
     * @SerializedName("Boulangerie")
     * @Assert\Type("Swagger\Server\Model\Boulangeries")
     * @Type("Swagger\Server\Model\Boulangeries")
     */
    protected $boulangerie;

    /**
     * nom responsable
     *
     * @var string|null
     * @SerializedName("nom")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $nom;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->boulangerie = isset($data['boulangerie']) ? $data['boulangerie'] : null;
        $this->nom = isset($data['nom']) ? $data['nom'] : null;
    }

    /**
     * Gets boulangerie.
     *
     * @return Swagger\Server\Model\Boulangeries|null
     */
    public function getBoulangerie()
    {
        return $this->boulangerie;
    }

    /**
     * Sets boulangerie.
     *
     * @param Swagger\Server\Model\Boulangeries|null $boulangerie
     *
     * @return $this
     */
    public function setBoulangerie(Boulangeries $boulangerie = null)
    {
        $this->boulangerie = $boulangerie;

        return $this;
    }

    /**
     * Gets nom.
     *
     * @return string|null
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Sets nom.
     *
     * @param string|null $nom  nom responsable
     *
     * @return $this
     */
    public function setNom($nom = null)
    {
        $this->nom = $nom;

        return $this;
    }
}


