<?php
/**
 * Livreurs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Livreurs model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Livreurs 
{
        /**
     * @var int|null
     * @SerializedName("matricule")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $matricule;

    /**
     * @var int|null
     * @SerializedName("teleLivreur")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $teleLivreur;

    /**
     * @var string
     * @SerializedName("numVehicule")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 20
     * )
     */
    protected $numVehicule;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->matricule = isset($data['matricule']) ? $data['matricule'] : null;
        $this->teleLivreur = isset($data['teleLivreur']) ? $data['teleLivreur'] : null;
        $this->numVehicule = isset($data['numVehicule']) ? $data['numVehicule'] : null;
    }

    /**
     * Gets matricule.
     *
     * @return int|null
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * Sets matricule.
     *
     * @param int|null $matricule
     *
     * @return $this
     */
    public function setMatricule($matricule = null)
    {
        $this->matricule = $matricule;

        return $this;
    }

    /**
     * Gets teleLivreur.
     *
     * @return int|null
     */
    public function getTeleLivreur()
    {
        return $this->teleLivreur;
    }

    /**
     * Sets teleLivreur.
     *
     * @param int|null $teleLivreur
     *
     * @return $this
     */
    public function setTeleLivreur($teleLivreur = null)
    {
        $this->teleLivreur = $teleLivreur;

        return $this;
    }

    /**
     * Gets numVehicule.
     *
     * @return string
     */
    public function getNumVehicule()
    {
        return $this->numVehicule;
    }

    /**
     * Sets numVehicule.
     *
     * @param string $numVehicule
     *
     * @return $this
     */
    public function setNumVehicule($numVehicule)
    {
        $this->numVehicule = $numVehicule;

        return $this;
    }
}


