<?php
/**
 * Produits
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Produits model.
 *
 * @package Swagger\Server\Model
 * @author  Swagger Codegen team
 */
class Produits 
{
        /**
     * @var int
     * @SerializedName("codeProduit")
     * @Assert\NotNull()
     * @Assert\Type("int")
     * @Type("int")
     */
    protected $codeProduit;

    /**
     * @var string|null
     * @SerializedName("libelle")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 20
     * )
     */
    protected $libelle;

    /**
     * @var double
     * @SerializedName("prixHA")
     * @Assert\NotNull()
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $prixHA;

    /**
     * @var double
     * @SerializedName("TVA")
     * @Assert\NotNull()
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $tVA;

    /**
     * @var double|null
     * @SerializedName("prixTTC")
     * @Assert\Type("double")
     * @Type("double")
     */
    protected $prixTTC;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->codeProduit = isset($data['codeProduit']) ? $data['codeProduit'] : null;
        $this->libelle = isset($data['libelle']) ? $data['libelle'] : null;
        $this->prixHA = isset($data['prixHA']) ? $data['prixHA'] : null;
        $this->tVA = isset($data['tVA']) ? $data['tVA'] : null;
        $this->prixTTC = isset($data['prixTTC']) ? $data['prixTTC'] : null;
    }

    /**
     * Gets codeProduit.
     *
     * @return int
     */
    public function getCodeProduit()
    {
        return $this->codeProduit;
    }

    /**
     * Sets codeProduit.
     *
     * @param int $codeProduit
     *
     * @return $this
     */
    public function setCodeProduit($codeProduit)
    {
        $this->codeProduit = $codeProduit;

        return $this;
    }

    /**
     * Gets libelle.
     *
     * @return string|null
     */
    public function getLibelle()
    {
        return $this->libelle;
    }

    /**
     * Sets libelle.
     *
     * @param string|null $libelle
     *
     * @return $this
     */
    public function setLibelle($libelle = null)
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * Gets prixHA.
     *
     * @return double
     */
    public function getPrixHA()
    {
        return $this->prixHA;
    }

    /**
     * Sets prixHA.
     *
     * @param double $prixHA
     *
     * @return $this
     */
    public function setPrixHA($prixHA)
    {
        $this->prixHA = $prixHA;

        return $this;
    }

    /**
     * Gets tVA.
     *
     * @return double
     */
    public function getTVA()
    {
        return $this->tVA;
    }

    /**
     * Sets tVA.
     *
     * @param double $tVA
     *
     * @return $this
     */
    public function setTVA($tVA)
    {
        $this->tVA = $tVA;

        return $this;
    }

    /**
     * Gets prixTTC.
     *
     * @return double|null
     */
    public function getPrixTTC()
    {
        return $this->prixTTC;
    }

    /**
     * Sets prixTTC.
     *
     * @param double|null $prixTTC
     *
     * @return $this
     */
    public function setPrixTTC($prixTTC = null)
    {
        $this->prixTTC = $prixTTC;

        return $this;
    }
}


