<?php
/**
 * AdministrateursTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * AdministrateursTest Class Doc Comment
 *
 * @category    Class */
// * @description Administrateurs
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdministrateursTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Administrateurs"
     */
    public function testAdministrateurs()
    {
        $testAdministrateurs = new Administrateurs();
    }

    /**
     * Test attribute "loginAdmin"
     */
    public function testPropertyLoginAdmin()
    {
    }

    /**
     * Test attribute "passwordAdmin"
     */
    public function testPropertyPasswordAdmin()
    {
    }

    /**
     * Test attribute "nomAdmin"
     */
    public function testPropertyNomAdmin()
    {
    }

    /**
     * Test attribute "teleAdmin"
     */
    public function testPropertyTeleAdmin()
    {
    }
}
