<?php
/**
 * CommandesLaboTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * CommandesLaboTest Class Doc Comment
 *
 * @category    Class */
// * @description CommandesLabo
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommandesLaboTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommandesLabo"
     */
    public function testCommandesLabo()
    {
        $testCommandesLabo = new CommandesLabo();
    }

    /**
     * Test attribute "idCommandesLabo"
     */
    public function testPropertyIdCommandesLabo()
    {
    }

    /**
     * Test attribute "codeProduit"
     */
    public function testPropertyCodeProduit()
    {
    }

    /**
     * Test attribute "libelle"
     */
    public function testPropertyLibelle()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "quantiteTotal"
     */
    public function testPropertyQuantiteTotal()
    {
    }
}
