<?php
/**
 * CompositionsProduitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * CompositionsProduitTest Class Doc Comment
 *
 * @category    Class */
// * @description CompositionsProduit
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CompositionsProduitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CompositionsProduit"
     */
    public function testCompositionsProduit()
    {
        $testCompositionsProduit = new CompositionsProduit();
    }

    /**
     * Test attribute "idComposition"
     */
    public function testPropertyIdComposition()
    {
    }

    /**
     * Test attribute "codeProduit"
     */
    public function testPropertyCodeProduit()
    {
    }

    /**
     * Test attribute "idComposant"
     */
    public function testPropertyIdComposant()
    {
    }

    /**
     * Test attribute "quantiteComp"
     */
    public function testPropertyQuantiteComp()
    {
    }
}
