<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2002
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
        $testInlineResponse2002 = new InlineResponse2002();
    }

    /**
     * Test attribute "idCommandeBL"
     */
    public function testPropertyIdCommandeBL()
    {
    }

    /**
     * Test attribute "creationDate"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "dueDate"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "idBoulangerie"
     */
    public function testPropertyIdBoulangerie()
    {
    }

    /**
     * Test attribute "nomBL"
     */
    public function testPropertyNomBL()
    {
    }

    /**
     * Test attribute "matricule"
     */
    public function testPropertyMatricule()
    {
    }

    /**
     * Test attribute "nom"
     */
    public function testPropertyNom()
    {
    }
}
