<?php
/**
 * ProduitsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Server\Tests\Model
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BoulangerieApi
 *
 * The Boulangerie finally debugged for use, hosting service might need to be adapted
 *
 * OpenAPI spec version: 1.0.0
 * Contact: leafyteam@notaRealCompany.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Server\Model;

/**
 * ProduitsTest Class Doc Comment
 *
 * @category    Class */
// * @description Produits
/**
 * @package     Swagger\Server\Tests\Model
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProduitsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Produits"
     */
    public function testProduits()
    {
        $testProduits = new Produits();
    }

    /**
     * Test attribute "codeProduit"
     */
    public function testPropertyCodeProduit()
    {
    }

    /**
     * Test attribute "libelle"
     */
    public function testPropertyLibelle()
    {
    }

    /**
     * Test attribute "prixHA"
     */
    public function testPropertyPrixHA()
    {
    }

    /**
     * Test attribute "tVA"
     */
    public function testPropertyTVA()
    {
    }

    /**
     * Test attribute "prixTTC"
     */
    public function testPropertyPrixTTC()
    {
    }
}
